//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlibanhang.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("quanlibanhang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _100060865_585466758748175_8320271728836083712_n {
            get {
                object obj = ResourceManager.GetObject("100060865_585466758748175_8320271728836083712_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _100060865_585466758748175_8320271728836083712_n1 {
            get {
                object obj = ResourceManager.GetObject("100060865_585466758748175_8320271728836083712_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _101197904_310671876595314_6533892292530213718_n {
            get {
                object obj = ResourceManager.GetObject("101197904_310671876595314_6533892292530213718_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _101197904_310671876595314_6533892292530213718_n1 {
            get {
                object obj = ResourceManager.GetObject("101197904_310671876595314_6533892292530213718_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _101746348_265830954632906_2885394192350052352_n {
            get {
                object obj = ResourceManager.GetObject("101746348_265830954632906_2885394192350052352_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _101746348_265830954632906_2885394192350052352_n1 {
            get {
                object obj = ResourceManager.GetObject("101746348_265830954632906_2885394192350052352_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _103106644_271000670681841_7631544987165084212_n {
            get {
                object obj = ResourceManager.GetObject("103106644_271000670681841_7631544987165084212_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _103419937_1896029317200204_4820255377494743722_n {
            get {
                object obj = ResourceManager.GetObject("103419937_1896029317200204_4820255377494743722_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _103670166_703990863720248_7941266939541251233_n {
            get {
                object obj = ResourceManager.GetObject("103670166_703990863720248_7941266939541251233_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _103726883_316155519385693_3645751451014160480_n {
            get {
                object obj = ResourceManager.GetObject("103726883_316155519385693_3645751451014160480_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _103726883_316155519385693_3645751451014160480_n1 {
            get {
                object obj = ResourceManager.GetObject("103726883_316155519385693_3645751451014160480_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _104003344_702692930306514_5633049298633917754_n {
            get {
                object obj = ResourceManager.GetObject("104003344_702692930306514_5633049298633917754_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _104003344_702692930306514_5633049298633917754_n1 {
            get {
                object obj = ResourceManager.GetObject("104003344_702692930306514_5633049298633917754_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _104474373_279713966482989_665623644424487267_n {
            get {
                object obj = ResourceManager.GetObject("104474373_279713966482989_665623644424487267_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _104802004_3066786870077240_6242164845899822084_n {
            get {
                object obj = ResourceManager.GetObject("104802004_3066786870077240_6242164845899822084_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _104940139_1768279189980049_777414289634688563_n {
            get {
                object obj = ResourceManager.GetObject("104940139_1768279189980049_777414289634688563_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _106112380_1214311175591236_7414086440709944322_n {
            get {
                object obj = ResourceManager.GetObject("106112380_1214311175591236_7414086440709944322_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107607119_1220930731575566_4375028894449214557_n {
            get {
                object obj = ResourceManager.GetObject("107607119_1220930731575566_4375028894449214557_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107668506_288526835724330_7337323111132855789_n {
            get {
                object obj = ResourceManager.GetObject("107668506_288526835724330_7337323111132855789_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107757328_308016110565668_2864493662587088080_n {
            get {
                object obj = ResourceManager.GetObject("107757328_308016110565668_2864493662587088080_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107757328_308016110565668_2864493662587088080_n1 {
            get {
                object obj = ResourceManager.GetObject("107757328_308016110565668_2864493662587088080_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107805326_721202078711369_5237229755089079036_n {
            get {
                object obj = ResourceManager.GetObject("107805326_721202078711369_5237229755089079036_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107810217_1142734896102676_1610783215569738211_n {
            get {
                object obj = ResourceManager.GetObject("107810217_1142734896102676_1610783215569738211_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107810217_1142734896102676_1610783215569738211_n1 {
            get {
                object obj = ResourceManager.GetObject("107810217_1142734896102676_1610783215569738211_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107828253_218207609330166_1475767129358879112_n {
            get {
                object obj = ResourceManager.GetObject("107828253_218207609330166_1475767129358879112_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107833952_2990981094283647_634754867931714858_n {
            get {
                object obj = ResourceManager.GetObject("107833952_2990981094283647_634754867931714858_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107833952_2990981094283647_634754867931714858_n1 {
            get {
                object obj = ResourceManager.GetObject("107833952_2990981094283647_634754867931714858_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107836955_713720362796153_2034375022358404543_n {
            get {
                object obj = ResourceManager.GetObject("107836955_713720362796153_2034375022358404543_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107866745_2761887010701618_6042220849989241032_n {
            get {
                object obj = ResourceManager.GetObject("107866745_2761887010701618_6042220849989241032_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107866745_2761887010701618_6042220849989241032_n1 {
            get {
                object obj = ResourceManager.GetObject("107866745_2761887010701618_6042220849989241032_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107887802_230386877938261_5586785257932256796_n {
            get {
                object obj = ResourceManager.GetObject("107887802_230386877938261_5586785257932256796_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107887802_230386877938261_5586785257932256796_n1 {
            get {
                object obj = ResourceManager.GetObject("107887802_230386877938261_5586785257932256796_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107919169_580983745934137_8976924598474795031_n {
            get {
                object obj = ResourceManager.GetObject("107919169_580983745934137_8976924598474795031_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107919169_580983745934137_8976924598474795031_n1 {
            get {
                object obj = ResourceManager.GetObject("107919169_580983745934137_8976924598474795031_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107943052_332838201058484_3260087807232808107_n {
            get {
                object obj = ResourceManager.GetObject("107943052_332838201058484_3260087807232808107_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107943052_332838201058484_3260087807232808107_n1 {
            get {
                object obj = ResourceManager.GetObject("107943052_332838201058484_3260087807232808107_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107957451_319275909479320_4061326691309134011_n {
            get {
                object obj = ResourceManager.GetObject("107957451_319275909479320_4061326691309134011_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107957451_319275909479320_4061326691309134011_n1 {
            get {
                object obj = ResourceManager.GetObject("107957451_319275909479320_4061326691309134011_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107957457_2344256439216012_2340946205240599100_n {
            get {
                object obj = ResourceManager.GetObject("107957457_2344256439216012_2340946205240599100_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107957457_2344256439216012_2340946205240599100_n1 {
            get {
                object obj = ResourceManager.GetObject("107957457_2344256439216012_2340946205240599100_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _108018879_620538908567193_9164398624458398695_n {
            get {
                object obj = ResourceManager.GetObject("108018879_620538908567193_9164398624458398695_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _108118449_317930489375378_343712601849213515_n {
            get {
                object obj = ResourceManager.GetObject("108118449_317930489375378_343712601849213515_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _108118449_317930489375378_343712601849213515_n1 {
            get {
                object obj = ResourceManager.GetObject("108118449_317930489375378_343712601849213515_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _108118449_317930489375378_343712601849213515_n2 {
            get {
                object obj = ResourceManager.GetObject("108118449_317930489375378_343712601849213515_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _108853948_1555843657930558_8735576542184286435_n {
            get {
                object obj = ResourceManager.GetObject("108853948_1555843657930558_8735576542184286435_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _108853948_1555843657930558_8735576542184286435_n1 {
            get {
                object obj = ResourceManager.GetObject("108853948_1555843657930558_8735576542184286435_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _108950415_1451383531726036_7412021308654908425_n {
            get {
                object obj = ResourceManager.GetObject("108950415_1451383531726036_7412021308654908425_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _109060686_2584487678533621_4286993009034228884_n {
            get {
                object obj = ResourceManager.GetObject("109060686_2584487678533621_4286993009034228884_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _109060686_2584487678533621_4286993009034228884_n1 {
            get {
                object obj = ResourceManager.GetObject("109060686_2584487678533621_4286993009034228884_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _109887665_2396247847349826_7185502050163398393_n {
            get {
                object obj = ResourceManager.GetObject("109887665_2396247847349826_7185502050163398393_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _109887665_2396247847349826_7185502050163398393_n1 {
            get {
                object obj = ResourceManager.GetObject("109887665_2396247847349826_7185502050163398393_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _41085366_1962856870686487_5315822739552993280_n {
            get {
                object obj = ResourceManager.GetObject("41085366_1962856870686487_5315822739552993280_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _64238805_2224976974253256_659187251263045632_n {
            get {
                object obj = ResourceManager.GetObject("64238805_2224976974253256_659187251263045632_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _64238805_2224976974253256_659187251263045632_n1 {
            get {
                object obj = ResourceManager.GetObject("64238805_2224976974253256_659187251263045632_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _64238805_2224976974253256_659187251263045632_n2 {
            get {
                object obj = ResourceManager.GetObject("64238805_2224976974253256_659187251263045632_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _80055241_537219543537212_2909371882367090688_n {
            get {
                object obj = ResourceManager.GetObject("80055241_537219543537212_2909371882367090688_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _83930263_2475799152677897_2598998402888892416_n {
            get {
                object obj = ResourceManager.GetObject("83930263_2475799152677897_2598998402888892416_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _83930263_2475799152677897_2598998402888892416_n1 {
            get {
                object obj = ResourceManager.GetObject("83930263_2475799152677897_2598998402888892416_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _89060247_1049880122062414_6815122370055897088_n {
            get {
                object obj = ResourceManager.GetObject("89060247_1049880122062414_6815122370055897088_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _89060247_1049880122062414_6815122370055897088_n1 {
            get {
                object obj = ResourceManager.GetObject("89060247_1049880122062414_6815122370055897088_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _89060247_1049880122062414_6815122370055897088_n2 {
            get {
                object obj = ResourceManager.GetObject("89060247_1049880122062414_6815122370055897088_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
